### PR TITLE
✏️ Fix #260, #263, and #265

### LINKED ISSUE #260: HttpClientException should be exported.
## Is your feature request related to a problem?
Yes. When i got `HttpClientException` from teledart, i couldn't catch it, because the exception class are not exported.

## Describe the solution you'd like
Refactor the `HttpClientException` out from `src/util/http_client.dart` and export it to the `teledart.dart`

Some code snippet would help? 
```dart
  Teledart teledart = Teledart(...);

  // This will throws HttpClientException with code 429, because its <10 minutes opened.
  teledart.close();
```

## Additional context
None.

### PR DESCRIPTION
**Pull request by HeySreelal**
Fix #260

The `HttpClientException` is now being exported with `teledart.dart`. This will let the users setup error handlers for the same.

### CODE REVIEW

**Comment by HeySreelal** [comment]
Just refactored the `test/` directory as well. The `test/TeleDart_test.dart` wasn't following the dart conventions and Linter wasn't too happy about it.

I just refactored the linter issue by renaming and adding one test. Let's consider adding more tests in the future.

**Comment by HeySreelal** [comment]
Added one more commit, making the methods `editMessageText`, `editMessageCaption`, `editMessageMedia`, `editMessageLiveLocation`, `stopMessageLiveLocation`, and `editMessageReplyMarkup` to have the return type `Future<dynamic>` to be able to return either `Message` or `bool` as per the documentation. (Fixes #263).

**Comment by DinoLeung** [comment]
Thanks for your hard work @HeySreelal I'll be looking into this PR this weekend.

**Comment by HeySreelal** [comment]
Also added fix for #265. Made the `replyMarkup` parameter in the `Telegram.stopPoll` method to be nullable as per the documentation.

**Pull request merged**
