### PR TITLE
Upgraded the versions of http and json annotation to null safety

### PR DESCRIPTION
**Pull request by FallenAngel97**

### CODE REVIEW

**Comment by Azzeccagarbugli** [comment]
I was trying to test your PR and I got in the following issue. Seems that the are still some incompatibility unfortunately  

```
lib/main.dart:25:6: Error: Method 'listen' cannot be called on 'Stream<TeleDartMessage>?' because it is potentially null.
 - 'Stream' is from 'dart:async'.
 - 'TeleDartMessage' is from 'package:teledart/src/teledart/model/message.dart' ('../../../.pub-cache/git/TeleDart-93efdcbe201530024f3aae0d2aca096e067a8384/lib/src/teledart/model/message.dart').
Try calling using ?. instead.

  _m.listen((event) {});
     ^^^^^^
```

**Comment by FallenAngel97** [comment]
@Azzeccagarbugli  I didn't have this error with my project when I updated the versions. 
Maybe related to Flutter SDK.
Feel free to take my PR and add your changes to submit a different PR

**Comment by Azzeccagarbugli** [comment]
Perfect, I just needed to add the `!` in the following snippet:

```
 teledart
        .onMessage(
          keyword: 'Fight for freedom',
        )! // The mistake was exactly this one!
        .listen(
          (message) => message.reply('Stand with Hong Kong'),
        );
```

Nice job @FallenAngel97 👏

**Comment by FallenAngel97** [comment]
Thanks. I think, @DinoLeung can merge it if it's code looks OK.

**Comment by DinoLeung** [comment]
Looks like an massive PR. Will look into this in the coming weekend

**Comment by DinoLeung** [comment]
Sorry guys @FallenAngel97 @Azzeccagarbugli I have to close this PR. After a closer look at the changes and the sound null safety concept, I have way too many commands wanted to make in the PR, and I have decided to do it again from ground up. Which gave me a chance to do a proper clean up and more importantly cross reference again the Telegram doc. See #176 

Thanks for both of your effort, this PR is truly inspiring.

**Pull request closed without merging**
