### PR TITLE
Manually stops the bot

### PR DESCRIPTION
**Pull request by glofru**

### CODE REVIEW

**Comment by DinoLeung** [comment]
I'm am not sure if these changes are making real benifits or not, as I would assume users should know exactly what they are doing. It might ended up confusing users by adding `stop()`. I am interest to see people's opinions.

**Comment by glofru** [comment]
I think it would be useful. You should stop the bot whenever you want, without stopping the program itself

**Comment by DinoLeung** [comment]
@glofru That's not what I meant, I was saying I expect developer who uses this library knows which method is using to get updates from telegram. The `stop` method here is basically an alias to `removeWebhook` and `removeLongPolling`, which does not provide significant imrpovements in terms of lines of code is reqired. Rather, by adding this method might confuse developers who's new to this library, since this function will run both `removeWebhook` and `removeLongPolling`, but only one of them takes effect, not to mention adding `stop` method will ended up having two ways to perfrom the same action.

Again this is my personal opinion, I'm looking forward to see more discussion on this thread.

**Comment by DinoLeung** [comment]
@glofru similar changes has been made to https://github.com/DinoLeung/TeleDart/pull/138 I'm going to close this PR

**Pull request closed without merging**
